// <auto-generated />
using System;
using AcademicTaskManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicTaskManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AcademicTaskManager.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descripción del Proyecto 1",
                            Name = "Proyecto 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descripción del Proyecto 2",
                            Name = "Proyecto 2"
                        });
                });

            modelBuilder.Entity("AcademicTaskManager.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Primera tarea",
                            DueDate = new DateTime(2026, 2, 6, 17, 13, 2, 424, DateTimeKind.Local).AddTicks(7040),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Tarea 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Segunda tarea",
                            DueDate = new DateTime(2026, 2, 13, 17, 13, 2, 424, DateTimeKind.Local).AddTicks(7059),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Tarea 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tercera tarea",
                            DueDate = new DateTime(2026, 2, 9, 17, 13, 2, 424, DateTimeKind.Local).AddTicks(7061),
                            IsCompleted = true,
                            ProjectId = 2,
                            Title = "Tarea 3"
                        });
                });

            modelBuilder.Entity("AcademicTaskManager.Models.TaskItem", b =>
                {
                    b.HasOne("AcademicTaskManager.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AcademicTaskManager.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
